# Generated by Django 4.2 on 2024-07-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ingrendients",
            new_name="ingredients",
        ),
    ]
