# Generated by Django 4.2 on 2024-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_ingrendients_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="spirit_types",
            field=models.CharField(
                choices=[
                    ("vodka", "Vodka"),
                    ("whiskey", "Whiskey"),
                    ("rum", "Rum"),
                    ("gin", "Gin"),
                    ("liquor", "Liquor"),
                    ("nonalcoholic", "Non-Alcoholic"),
                ],
                default="gin",
                max_length=100,
            ),
        ),
    ]
